# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        # QApplication.desktop()
        style_sheet = """
                        QMenu{
                            font-size: 14px;
                        }
                        QMenuBar { 
                            font-size: 14px;
                        }
                        """
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # self.centralwidget.setStyleSheet("background-color: white")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1171, 23))
        self.menubar.setStyleSheet("""  
            QMenuBar {  
                font-size: 12pt;  
            }
            QMenu { font-size: 11pt; }
        """)
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        self.action_UC03 = QtWidgets.QAction(MainWindow)
        self.action_UC03.setObjectName("action_UC03")
        self.action_UC02 = QtWidgets.QAction(MainWindow)
        self.action_UC02.setObjectName("action_UC02")
        self.action_UC04 = QtWidgets.QAction(MainWindow)
        self.action_UC04.setObjectName("action_UC04")
        self.action_UC05 = QtWidgets.QAction(MainWindow)
        self.action_UC05.setObjectName("action_UC05")
        self.action_UC06 = QtWidgets.QAction(MainWindow)
        self.action_UC06.setObjectName("action_UC06")
        self.action_UC07 = QtWidgets.QAction(MainWindow)
        self.action_UC07.setObjectName("action_UC07")
        self.action_UC08 = QtWidgets.QAction(MainWindow)
        self.action_UC08.setObjectName("action_UC08")
        self.action_UC09 = QtWidgets.QAction(MainWindow)
        self.action_UC09.setObjectName("action_UC09")

        self.action_UC10 = QtWidgets.QAction(MainWindow)
        self.action_UC10.setObjectName("action_UC10")
        # self.action_UC11 = QtWidgets.QAction(MainWindow)
        # self.action_UC11.setObjectName("action_UC11")
        self.action_UC12 = QtWidgets.QAction(MainWindow)
        self.action_UC12.setObjectName("action_UC12")
        # self.action_UC13 = QtWidgets.QAction(MainWindow)
        # self.action_UC13.setObjectName("action_UC13")
        self.action_UC14 = QtWidgets.QAction(MainWindow)
        self.action_UC14.setObjectName("action_UC14")
        self.action_UC15 = QtWidgets.QAction(MainWindow)
        self.action_UC15.setObjectName("action_UC15")
        self.action_UC16 = QtWidgets.QAction(MainWindow)
        self.action_UC16.setObjectName("action_UC16")

        self.action_UC17 = QtWidgets.QAction(MainWindow)
        self.action_UC17.setObjectName("action_UC17")
        self.action_UC18 = QtWidgets.QAction(MainWindow)
        self.action_UC18.setObjectName("action_UC18")
        self.action_UC19 = QtWidgets.QAction(MainWindow)
        self.action_UC19.setObjectName("action_UC19")
        self.action_UC20 = QtWidgets.QAction(MainWindow)
        self.action_UC20.setObjectName("action_UC20")


        self.action_UC21 = QtWidgets.QAction(MainWindow)
        self.action_UC21.setObjectName("action_UC21")
        self.action_UC22 = QtWidgets.QAction(MainWindow)
        self.action_UC22.setObjectName("action_UC22")
        self.action_UC23 = QtWidgets.QAction(MainWindow)
        self.action_UC23.setObjectName("action_UC23")
        self.action_UC24 = QtWidgets.QAction(MainWindow)
        self.action_UC24.setObjectName("action_UC24")
        self.action_UC25 = QtWidgets.QAction(MainWindow)
        self.action_UC25.setObjectName("action_UC25")
        self.action_UC27 = QtWidgets.QAction(MainWindow)
        self.action_UC27.setObjectName("action_UC27")
        self.action_UC28 = QtWidgets.QAction(MainWindow)
        self.action_UC28.setObjectName("action_UC28")
        self.action_UC29 = QtWidgets.QAction(MainWindow)
        self.action_UC29.setObjectName("action_UC29")
        self.action_UC30 = QtWidgets.QAction(MainWindow)
        self.action_UC30.setObjectName("action_UC30")
        self.action_UC31 = QtWidgets.QAction(MainWindow)
        self.action_UC31.setObjectName("action_UC31")
        self.action_UC32 = QtWidgets.QAction(MainWindow)
        self.action_UC32.setObjectName("action_UC32")
        self.action_UC33 = QtWidgets.QAction(MainWindow)
        self.action_UC33.setObjectName("action_UC33")

        self.menu_1.addAction(self.action_UC03)
        self.menu_1.addAction(self.action_UC02)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_UC04)
        self.menu_1.addAction(self.action_UC05)
        self.menu_1.addAction(self.action_UC06)
        self.menu_1.addAction(self.action_UC07)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.action_UC08)
        self.menu_1.addAction(self.action_UC09)

        self.menu_2.addAction(self.action_UC10)
        # self.menu_2.addAction(self.action_UC11)
        self.menu_2.addAction(self.action_UC12)
        self.menu_2.addSeparator()
        # self.menu_2.addAction(self.action_UC13)
        self.menu_2.addAction(self.action_UC14)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_UC15)
        self.menu_2.addSeparator()
        # self.menu_2.addAction(self.action_UC13)
        self.menu_2.addAction(self.action_UC16)

        self.menu_3.addAction(self.action_UC17)
        self.menu_3.addAction(self.action_UC18)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_UC19)
        self.menu_3.addAction(self.action_UC20)

        self.menu_4.addAction(self.action_UC21)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_UC22)
        self.menu_4.addAction(self.action_UC23)
        self.menu_4.addAction(self.action_UC24)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_UC25)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_UC27)
        self.menu_4.addAction(self.action_UC28)
        self.menu_4.addAction(self.action_UC29)
        self.menu_4.addAction(self.action_UC30)
        self.menu_4.addAction(self.action_UC31)
        self.menu_4.addAction(self.action_UC32)
        self.menu_4.addAction(self.action_UC33)

        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        MainWindow.setStyleSheet(style_sheet)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于人工智能的临床脑电大数据平台"))
        # self.label.setText(_translate("MainWindow", "当前位置："))
        # self.label_3.setText(_translate("MainWindow", "当前用户："))
        # self.label_2.setText(_translate("MainWindow", "当前身份："))
        self.menu_1.setTitle(_translate("MainWindow", "系统功能"))
        self.menu_2.setTitle(_translate("MainWindow", "日常/远程诊断"))
        self.menu_3.setTitle(_translate("MainWindow", "脑电诊断培训"))
        self.menu_4.setTitle(_translate("MainWindow", "脑电科研支撑"))
        self.action_UC03.setText(_translate("MainWindow", "用户管理"))
        self.action_UC02.setText(_translate("MainWindow", "密码修改"))
        self.action_UC04.setText(_translate("MainWindow", "标注类型"))
        self.action_UC05.setText(_translate("MainWindow", "基本配置"))
        self.action_UC06.setText(_translate("MainWindow", "配置选择"))
        self.action_UC07.setText(_translate("MainWindow", "导联配置"))
        self.action_UC08.setText(_translate("MainWindow", "切换用户"))
        self.action_UC09.setText(_translate("MainWindow", "退出"))

        self.action_UC10.setText(_translate("MainWindow", "病人管理"))
        # self.action_UC11.setText(_translate("MainWindow", "病人查询"))
        self.action_UC12.setText(_translate("MainWindow", "导入脑电"))
        # self.action_UC13.setText(_translate("MainWindow", "标注诊断"))
        self.action_UC14.setText(_translate("MainWindow", "诊断查询"))
        self.action_UC15.setText(_translate("MainWindow", "创建会诊"))
        self.action_UC16.setText(_translate("MainWindow", "脑电诊断"))

        self.action_UC17.setText(_translate("MainWindow", "创建课堂"))
        self.action_UC18.setText(_translate("MainWindow", "诊断学习"))
        self.action_UC19.setText(_translate("MainWindow", "学习测试"))
        self.action_UC20.setText(_translate("MainWindow", "学习评估"))

        self.action_UC21.setText(_translate("MainWindow", "样本统计"))
        self.action_UC22.setText(_translate("MainWindow", "任务设置"))
        self.action_UC23.setText(_translate("MainWindow", "科研标注"))
        self.action_UC24.setText(_translate("MainWindow", "执行查看"))
        self.action_UC25.setText(_translate("MainWindow", "集合管理"))
        self.action_UC27.setText(_translate("MainWindow", "算法管理"))
        self.action_UC28.setText(_translate("MainWindow", "模型训练"))
        self.action_UC29.setText(_translate("MainWindow", "模型测试"))
        self.action_UC30.setText(_translate("MainWindow", "模型管理"))
        self.action_UC31.setText(_translate("MainWindow", "脑电扫描"))
        self.action_UC32.setText(_translate("MainWindow", "评估样本"))
        self.action_UC33.setText(_translate("MainWindow", "清理样本"))
