# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_channels.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_channels(object):
    def setupUi(self, add_channels):
        add_channels.setObjectName("add_channels")
        add_channels.resize(303, 105)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_channels.sizePolicy().hasHeightForWidth())
        add_channels.setSizePolicy(sizePolicy)
        add_channels.setMaximumSize(QtCore.QSize(16777215, 1400))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(add_channels)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(add_channels)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(add_channels)
        self.lineEdit.setMaxLength(18)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(add_channels)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(add_channels)
        self.lineEdit_2.setMaxLength(18)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(add_channels)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)

        self.retranslateUi(add_channels)
        QtCore.QMetaObject.connectSlotsByName(add_channels)

    def retranslateUi(self, add_channels):
        _translate = QtCore.QCoreApplication.translate
        add_channels.setWindowTitle(_translate("add_channels", "Form"))
        self.label.setText(_translate("add_channels", "测量通道"))
        self.label_2.setText(_translate("add_channels", "参考通道"))
        self.pushButton.setText(_translate("add_channels", "确认"))
