#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect

class Ui_diagList(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 1060)

        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setStyleSheet("font: 20px;border:none;border-bottom:1px solid rgb(210, 210, 210)")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setGeometry(QRect(5, 40, 1080, 1060))

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)


        self.tableWidget.verticalHeader().setStretchLastSection(False)
        #self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout.addWidget(self.tableWidget)
        # spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout.addItem(spacerItem1)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Ui_diagList", "[标注诊断]未诊断信息列表"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Ui_diagList", "检查单号"))
        self.tableWidget.setColumnWidth(0, 160)

        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Ui_diagList", "病人"))
        self.tableWidget.setColumnWidth(1, 120)

        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Ui_diagList", "测量日期"))
        self.tableWidget.setColumnWidth(2, 160)

        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Ui_diagList", "医生"))
        self.tableWidget.setColumnWidth(3, 160)

        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Ui_diagList", "操作"))
        self.tableWidget.setColumnWidth(4, 240)

