# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_progressbar(object):
    def __init__(self, window_title):
        self.window_title = window_title
        self.pb = None
    def setupUi(self, progressbar):
        progressbar.setObjectName("processbar")
        progressbar.resize(470, 140)
        self.pb = progressbar
        self.progressBar = QtWidgets.QProgressBar(progressbar)
        self.progressBar.setGeometry(QtCore.QRect(20, 50, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.stop_pushButton = QtWidgets.QPushButton(progressbar)
        self.stop_pushButton.setGeometry(QtCore.QRect(190, 100, 75, 23))
        self.stop_pushButton.setObjectName("stop_pushButton")

        self.retranslateUi(progressbar)
        QtCore.QMetaObject.connectSlotsByName(progressbar)

    def retranslateUi(self, processbar):
        _translate = QtCore.QCoreApplication.translate
        processbar.setWindowTitle(_translate("processbar", self.window_title))
        self.stop_pushButton.setText(_translate("processbar", "取消"))

